<?php
error_reporting(E_ALL ^ E_NOTICE);

if (file_exists("../../../data/api/".$_POST["file"]))
	die();
	
ob_start();

$name = $_POST['name'];
$params = json_decode($_POST["params"], true);

$defined = $_POST["defined"];

?><?php echo $name."\n"; ?>=============

@todo:
	check the autogenerated stub

@short:
	<?php echo $params["descr"]; ?>


@params:
<?php
foreach ($params as $key => $value) { 
	if ($key!="descr")
		echo "- ".$key."\t\tany\t\t".$value."\n";
}
?>

@example:


@template:	api_event
@descr:

<?php
$code = ob_get_contents();
file_put_contents("../../../data/api/".$_POST["file"],$code);

?>