<?php
error_reporting(E_ALL ^ E_NOTICE);

if (file_exists("../../../data/api/".$_POST["file"]))
	die();

ob_start();

$name = $_POST['name'];
$params = json_decode($_POST["params"], true);

$signature = array();
for ($i=0; $i < sizeof($params); $i++) { 
	$signature[]=$params[$i]["name"];
}
$returns = $_POST["returns"];
$defined = $_POST["defined"];
$descr = $_POST["descr"];

?>
<?php echo $name."\n"; ?>=============


@todo:
	check the autogenerated stub

@short:
	<?php echo $descr; ?>


@params:
<?php
for ($i=0; $i < sizeof($params); $i++) { 
	echo "- ".$params[$i]["name"]."\t\t".$params[$i]["assert"]."\t\t".$params[$i]["descr"]."\n";
}
?>


<?php if ($returns) { ?>
@returns:
	<?php echo $returns; ?>
<?php } ?>



@example:

@template:	api_method
@descr:

<?php
$code = ob_get_contents();
file_put_contents("../../../data/api/".$_POST["file"],$code);

?>