<?php
error_reporting(E_ALL ^ E_NOTICE);

if (file_exists("../../../data/api/".$_POST["file"]))
	die();

ob_start();

$name = $_POST['name'];
$params = json_decode($_POST["params"], true);

$defined = $_POST["defined"];
$descr = $_POST["descr"];

?><?php echo $name."\n"; ?>=============

@todo:
	check the autogenerated stub


@short:
	<?php echo $descr; ?>


@type:

@example:

@template:	api_template
@descr:


<?php
$code = ob_get_contents();
file_put_contents("../../../data/api/".$_POST["file"],$code);

?>